language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - "pip install -U pip"
install:
  - "pip install -e .[test]"
script:
  - "py.test tests/"
  - "pep8 apt_repoman/"
